### ISSUE TITLE
merge explorer-server with newsanalysis repo?

### ISSUE THREAD

**Issue by Tilana** [MediaUncovered/explorer-server#3]
Discussion about merging the explorer-server with the newsanalysis repo to:
- automatize the pipeline
- avoid copying the sample model
- reusing code
- reducing the number of required modules

**Comment by todorus** [comment]
"The value of separation of concerns is simplifying development and maintenance of computer programs. When concerns are well-separated, individual sections can be reused, as well as developed and updated independently. Of special value is the ability to later improve or modify one section of code without having to know the details of other sections, and without having to make corresponding changes to those sections." (see https://en.wikipedia.org/wiki/Separation_of_concerns)

So for me this isn't much of a discussion. It's a well established design principle in computer science and I have experienced first hand the problems that pop up when you don't seperate these concerns. The api is now designed to handle http requests and act as an interface to the model. It does not implement any business logic. This is a very nice design and we would do well to keep it that way.

**Comment by Tilana** [comment]
The thing is that the server is completely dependent of the word embedding model itself. As soon as a functionality is changed, added, or removed we have to create a new model, copy it to the server, package the model code to access the changes from the server, update the server itself, test it again, and if necessary update the docker environment....
There is no way to 'develop and update them independently'. So, I don't see that the principle of separating concerns applies

**Comment by todorus** [comment]
The model shouldn't be packaged with the server into a docker image, as that would make that impossible, yeah. The server should be packed into the image, and the model should be referenced to using a docker volume. This way we can keep the server running while changing out models.

**Comment by todorus** [comment]
Ah when the interface changes. Well yeah and that's still a good idea, as there are two seperate concerns. If we don't know a way to keep them seperate, that would be more a mistake on our side then anything else. So now the burden falls upon me to proof this concept in this specific case? I don't think a lack of foresight should be a reason to merge these things. It is *really* good practice.

And in our specific case I've already said it before: we have multiple applications that need this functionality, not just the server. I would appreciate if you wouldn't keep trying to bring this up and us having going through the same arguments again

**Comment by Tilana** [comment]
It might be good practice, however the way we implemented it is totally impractical and frustrating.
If restructuring the components is not possible, we definitively need a way to automatize this process.
